### ISSUE TITLE
Xcode 8.3 Support

### ISSUE THREAD

**Issue by zac** [goodpatch/Balto-SDK#2]
Hello! We'd like to integrate Balto into a project that's using Xcode 8.3 and Swift 3.1. It appears like currently the Balto SDK is built using Swift 3.0.2.

```
Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: Carthage/Build/iOS/BaltoSDK.framework/Modules/BaltoSDK.swiftmodule/x86_64.swiftmodule
```

Is there a plan to re-compile with Swift 3.1? Thanks!

**Comment by HirokiTerashima0816** [comment]
@zac Hi there. We've just updated the SDK and now it's available with Swift 3.1.
Thanks!
